#2. Algoritmo para ir ao banco para sacar dinheiro (Imprimir a sequência para ir ao banco e sacar dinheiro)

print('Dirija-se ao banco ou caixa eletrônico')
print('Verifique se o caixa eletrônico aceita a bandeira do seu cartão')
print('Insira o cartão com a parte frontal virada para cima no local indicado no caixa eletrônico')
print('Digite sua senha')
print('Retire o cartão quando a máquina solicitar')
print('Selecione a opção "Saque" no menu principal')
print('Selecione a quantia que gostaria de sacar')
print('Pressione a tecla "Enter" ou "Confirma"')
print('Aguarde a máquina processar a transação')
print('Decida se quer ou não imprimir o comprovante pressionando o botão ou toque na tela nas opções "Sim" ou "Não"')
print('Retire o dinheiro e o comprovante (caso solicitado) nos locais indicados')
print('Decida de gostaria de realizar outra transação ou finalize a operação. Banco X agradece a preferência!')