#3. Algoritmo para trocar o pneu do carro (Imprimir a sequência para trocar o pneu do carro)

print('Parar o carro')
print('Puxar o freio de mão')
print('Tirar o cinto de segurança')
print('Abrir a porta e sair do carro')
print('Abrir o porta malas')
print('Retirar o estepe, macado e chave de roda')
print('Fechar o porta malas')
print('Afrouxar os parafusos da roda do pneu a ser trocado usando a chave de roda')
print('Encaixar o macaco embaixo do carro e suspendê-lo')
print('Desenroscar os parafusos da roda')
print('Remover o pneu a ser trocado')
print('Colocar o estepe no lugar')
print('Colocar os parafusos')
print('Abaixar o carro utilizando o macaco')
print('Apertar bem os parafusos com a chave de roda')
print('Abrir o porta malas')
print('Guardar o macaco, chave de roda e o pneu furado')
print('Fechar o porta malas')